FORMAT: 1A
HOST: http://www.google.com

# Evil character API 
http://unicodelookup.com/#32994/1


# Get evil character [GET]
+ Response 200 (application/json)

        {
          "i_am_the_evil_character": " "
        }